### PR TITLE
Feature/ldap login

### PR DESCRIPTION
**Pull request by fnc11**
1. Fixed folder scanning issue with @ symbol
2. Shifted to Spring-Boot
3. Fixed the admin password change issue
4. Added LDAP Authentication, now you can specify the LDAP server address and common name of the exclusive group to authenticate via LDAP

### CODE REVIEW

**Comment by fnc11** [comment]
Just found one issue, which went unnoticed earlier, whenever any video is played after login the app doesn't let the user see any more files and on-page reload sends them to login page again. Still figuring out why this is happening, logs don't show any unusual behaviour.

**Comment by fnc11** [comment]
@pjreed 

Can you help me with this issue, there's no error or exception in logs. The issue is explained in [detail]([url](https://stackoverflow.com/questions/61646421/websocket-sessions-end-also-destroys-http-session)) here. Basically, after Ldap login when the user plays any video from bag files, that video is played but then they are required to login again before accessing any other file's details.

**Comment by pjreed** [comment]
Do you have any instructions for setting up a simple LDAP server to test this with?  I'm not very familiar with LDAP, so it might take a little work for me to get a test environment set up.

I feel like I have seen an error like this before, but it's been a long time.  I suspect that something is either throwing an exception internally that isn't being logged, or the web browser is trying to access a resource that it does not have permission to access, and that is causing the user's session to be marked as invalid, which forces them to log in again.  If I can get a test environment working, I'll experiment with it to see if I can figure out where the problem is.

**Comment by fnc11** [comment]
Okay, I'll provide a link for the instructions to set up OpenLDAP server locally on your machine, then you can check the error with this [code ](https://github.com/fnc11/bag-database/tree/feature/openLdap_login) where I implemented with OpenLDAP.

**Comment by fnc11** [comment]
I have specified instructions to set up an openLDAP server locally at the end part of the read.md file on the feature/openLdap_login [branch](https://github.com/fnc11/bag-database/tree/feature/openLdap_login). Let me know if you need anything from my side.

And this is the StackOverflow question [link](https://stackoverflow.com/questions/61646421/websocket-sessions-end-also-destroys-http-session), it was missed earlier.

**Comment by fnc11** [comment]
And of course this openLdap server will work with the code in that same branch because the Security Configuration file is configured in respect to openLdap server (address and organisation name) that's why I write the instructions in that branch.

Just as information.

**Comment by pjreed** [comment]
Thanks, I was able to get an LDAP server working, and I can confirm that I see the same issue as you.  I'll investigate and let you know if I figure out anything more about what's going wrong.

**Comment by pjreed** [comment]
Ok, I think I figured out the problem.  The service call that was streaming the video was never returning, and that was causing an error in the web server that was invalidating the user's session.  I made it return a value, and now it looks better.

I made a PR for that and some other changes to your `openLdap_login` branch, although I just noticed that one has diverged from the branch in this PR, so if you would prefer, I'll rebase my PR to make it target your `feature/ldap_login` branch instead.

**Comment by fnc11** [comment]
First a big thank for finding and solving the issue.

And about the PR if you have time then please do it otherwise I can cherry-pick these changes to the `feature/ldap_login` branch. But I was thinking about why it diverged in the first place, you added your changes on top of my changes right in the `feature/openLdap_branch`.

**Comment by pjreed** [comment]
Ok, I've tested all of this and I think it's all good now.  Thank you again for your work!

**Pull request merged**
